runtime: python312
instance_class: F4

entrypoint: python main.py --server.port 8501

env_variables:
  PYTHONUNBUFFERED: "true"
  STREAMLIT_BROWSER_GATHER_USAGE_STATS: "false"
  STREAMLIT_CLIENT_TOOLING: "false"
  STREAMLIT_SERVER_FILE_WATCHER_TYPE: "none"

handlers:
- url: /.*
  script: auto
  secure: always

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2
  target_throughput_utilization: 0.6
  max_concurrent_requests: 80

readiness_check:
  app_start_timeout_sec: 300
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  initial_delay_sec: 300
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2